=== CEINMS/CEINMS/cfg/XSD/execution.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Authors: Elena Ceseracciu, Claudio Pizzolato, Monica Reggiani -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="en"/>
  </xs:annotation>
  <xs:complexType name="TendonElementType"/>
  <xs:complexType name="TendonType">
    <xs:choice>
      <xs:element name="stiff" type="TendonElementType"/>
      <xs:element name="integrationElastic" type="TendonElementType"/>
      <xs:element name="equilibriumElastic" type="TendonElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ActivationElementType"/>
  <xs:complexType name="ActivationType">
    <xs:choice>
      <xs:element name="exponential" type="ActivationElementType"/>
      <xs:element name="piecewise" type="ActivationElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="SimulatedAnnealingType">
    <xs:sequence>
      <xs:element name="noEpsilon" type="xs:int"/>
      <xs:element name="rt" type="xs:double"/>
      <xs:element name="T" type="xs:double"/>
      <xs:element name="NS" type="xs:int"/>
      <xs:element name="NT" type="xs:int"/>
      <xs:element name="epsilon" type="xs:double"/>
      <xs:element name="maxNoEval" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HybridAlgorithmType">
    <xs:choice>
      <xs:element name="simulatedAnnealing" type="SimulatedAnnealingType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="OpenLoopType"/>
  <xs:simpleType name="MuscleListType">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>
  <xs:complexType name="HybridType">
    <xs:sequence>
      <xs:element name="alpha" type="xs:double"/>
      <xs:element name="beta" type="xs:double"/>
      <xs:element name="gamma" type="xs:double"/>
      <xs:element name="trackedMuscles" type="MuscleListType"/>
      <xs:element name="predictedMuscles" type="MuscleListType"/>
      <xs:element name="algorithm" type="HybridAlgorithmType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TypeType">
    <xs:choice>
      <xs:element name="openLoop" type="OpenLoopType"/>
      <xs:element name="hybrid" type="HybridType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="NMSModelType">
    <xs:sequence>
      <xs:element name="type" type="TypeType"/>
      <xs:element name="tendon" type="TendonType"/>
      <xs:element name="activation" type="ActivationType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="ElaboratedDoFsType">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>
  <xs:complexType name="ExecutionElementType"/>
  <xs:complexType name="FileType"/>
  <xs:complexType name="LoggingType">
    <xs:choice>
      <xs:element name="txt" type="FileType"/>
      <xs:element name="csv" type="FileType"/>
      <xs:element name="mot" type="FileType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ExecutionType">
    <xs:sequence>
      <xs:element name="NMSmodel" type="NMSModelType"/>
      <xs:choice>
        <xs:element name="online" type="ExecutionElementType"/>
        <xs:element name="offline" type="ExecutionElementType"/>
      </xs:choice>
      <xs:element minOccurs="0" name="elaboratedDoFs" type="ElaboratedDoFsType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="execution" type="ExecutionType"/>
</xs:schema>

=== CEINMS/CEINMS/TestCfg/Execution/executionTestHybrid.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<execution xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="execution.xsd">
  <NMSmodel>
     <type>
        <hybrid>
            <alpha> 1 </alpha>
              <beta> 2 </beta>
              <gamma> 3 </gamma> 
              <trackedMuscles> 
                               recfem_r vasmed_r vaslat_r vasint_r bicfemsh_r 
                               gmin1_r gmin2_r gmin3_r gmed1_r gmed2_r gmed3_r 
                               tfl_r addbrev_r addlong_r addmag1_r addmag2_r 
                               addmag3_r gra_r sar_r semiten_r semimem_r bicfemlh_r 
                               gmax1_r gmax2_r gmax3_r gaslat_r gasmed_r sol_r perlong_r 
                               tibant_r perter_r perbrev_r  
              </trackedMuscles>
              <predictedMuscles> psoas_r illiacus_r</predictedMuscles> 
              <algorithm>
                   <simulatedAnnealing>
                        <noEpsilon>4</noEpsilon>
                        <rt>0.3</rt>
                        <T>20</T>
                        <NS>15</NS>
                        <NT>5</NT>
                        <epsilon>1.E-3</epsilon>
                        <maxNoEval>200000</maxNoEval>
                   </simulatedAnnealing>
              </algorithm>
        </hybrid>
     </type>

     <tendon>
          <stiff/>
     </tendon>

     <activation>
          <exponential/>
     </activation>
  </NMSmodel>

  <online/>

  <samplingFrequency>
  200
  </samplingFrequency>

  <elaboratedDoFs>
     PugnoFotonico AlabardaSpaziale 
  </elaboratedDoFs>

  <logging>
     <txt/>
  </logging>


</execution>

=== CEINMS/CEINMS/TestCfg/Execution/executionTestOL.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<execution xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="execution.xsd">

  <NMSmodel>
    <type>
      <openLoop/>
    </type>
    <tendon>
      <stiff/>
    </tendon>
    <activation>
      <exponential/>
    </activation>
  </NMSmodel>

  <offline/>

</execution>
